title: Jamie Cui
logo: /assets/img/IMG_20200615_132439.jpg
description: jamie [dot] cui [at] outlook.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

site:
  author: Jamie-Cui
